global:
  scrape_interval: 5s
  evaluation_interval: 5s 
scrape_configs:
  - job_name: 'catalog'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['catalog:8010']
  - job_name: 'scheduleservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['scheduleservice:8050']
  - job_name: 'bookingservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['bookingservice:8000']
